create schema if not exists company_a;
create schema if not exists company_b;

CREATE TABLE IF NOT EXISTS company_a.PRODUCTS (
   id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   description VARCHAR(255),
    name        VARCHAR(255),
    price       NUMERIC(38, 2)
    );


CREATE TABLE IF NOT EXISTS company_b.PRODUCTS (
     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     description VARCHAR(255),
    name        VARCHAR(255),
    price       NUMERIC(38, 2)
    );

