server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/lungnd/config-repo
#          search-paths:
#            - tenant
          clone-on-start: true
